version: "3.3"

services:
  dev:
    container_name: trex
    image: trexnode.azurecr.io/trex-node:latest
    working_dir: /rustbuilder
    ports:
      - "9933:9933"
      - "9944:9944"
      - "30333:30333"
    environment:
      - CARGO_HOME=/rustbuilder/.cargo
    volumes:
      - .:/data
      - type: bind
        source: ./.local
        target: /root/.local
    command: --dev --ws-external --rpc-cors all --rpc-methods=unsafe --rpc-external
